### ISSUE TITLE
Request 'twitch.py' package ownership on PyPi

### ISSUE THREAD

**Issue by mrsnifo** [sleibrock/twitch.py#1]
Hi Slei,

I noticed that the 'twitch.py' package on PyPI ([https://pypi.org/project/ twitch.py/](https://pypi.org/project/twitch.py/)) hasn't been updated for some time. I am currently working on a library for twitch.com called twithify and would love to take over the 'twitch.py' package name if you are no longer using it.
Since my project is open-source, I believe it could benefit the community greatly. If you are willing to transfer the name, I would be very grateful.
Thank you for your consideration.

**Comment by mrsnifo** [comment]
I've tried emailing you, tho it says that email does not exists anymore

**Comment by ste5e99** [comment]
Hey, sorry for not replying sooner. I am generally not on my computer during the week and I apologize for the delay.

I appreciate the interest in taking over the `twitch.py` package. It has been a number of years since I have worked on the package itself, or even really had any interest in Twitch as a platform, so I would be happy to start the take-down process of my package(s) to get you started.

Since I started uploading packages to Python, I have lost access to that old email of mine and had to start a new one. I, sadly, do not have the login combination to log into the account, so I have started the process of trying to recover it via PyPI's support channels. I have read a bit of your source code and I think I can deem it trustworthy enough to let this transfer over without worries of a possible security threat (think `xz-lib`...). There's definitely nobody using it, and I couldn't update it even if I wanted to.

I will keep you posted if and when I get access into my PyPI account so I can start archiving this and other packages of mine, simply because it's been an item on my todo list for too long so I will try to kick that off as soon as I can.

Cheers and talk soon.

**Comment by mrsnifo** [comment]
Hey Slei,

Thanks a lot for getting back to me! I totally understand the delay and the situation with the old email. I really appreciate you taking the time to start the recovery process and your willingness to transfer the package. It means a lot!

I’m glad you had a chance to check out my project, and I’m happy to assist with anything you might need to make the transition as easy as possible.

Looking forward to hearing from you when you're ready!

**Comment by mrsnifo** [comment]
Hi @sleibrock,

Any updates ?

**Comment by ste5e99** [comment]
Hey again,

Just received an update from PyPI about account recovery. Will let you know when I get back in. Sorry for the delay.

**Comment by mrsnifo** [comment]
Hi @sleibrock,

Thanks for the update! I appreciate your efforts on the account recovery. Let me know if I can help in any way.

**Comment by ste5e99** [comment]
Hey again, just to keep you updated...

I started an account recovery process with PyPI but I have yet to hear back on the next steps. I have done what they have asked as part of their process but I suspect it may take some time for someone to check the emails...

Will keep you posted when I get a response, hopefully sooner rather than later.

**Comment by mrsnifo** [comment]
Thank you for the update! I really appreciate you taking the time to keep me informed. I'll stay patient, and I’m grateful for your efforts. Looking forward to hearing more when there’s news.

**Comment by ste5e99** [comment]
Hey again,

I guess by mentioning it, the process completed overnight and I am now logged in. I work full time and I don't have enough time to do it right away but I can do it when I come home. I'll let you know when the package is unpublished.

**Comment by mrsnifo** [comment]
Alright, just wanted to let you know that you won’t be able to delete the package. Instead, you'll need to add me as a collaborator with the "Owner" role. You can do this in the package settings. That’s all we need to do because if the package is deleted, I won’t be able to recreate it since the name can only be used once. Thanks for understanding!

**Comment by mrsnifo** [comment]
My pypi username is Snifo

https://pypi.org/user/Snifo/

**Comment by ste5e99** [comment]
Hey, sorry for the delay. I have gone ahead and made you the owner of the project on PyPI now. Once you get settled in, I will archive this repository and (hopefully) take myself off as owner so it will be fully yours.

**Comment by mrsnifo** [comment]
Hey, thanks a lot for transferring ownership! I appreciate all the work you've put into. Once I’m settled in, feel free to archive the repo and remove yourself as the owner. I’ll take it from there. Thanks again! Much love <3

**Comment by ste5e99** [comment]
Hey again, I've gone ahead and removed myself from the owners role. Good luck with everything! I'll be watching from a safe distance.

**Comment by mrsnifo** [comment]
Got it, and thanks for everything! I’ll make sure to take good care of it. If you need anything, just let me know.
